---
# handlers file for ansible-role-prometheus
- name: reload prometheus
  service:
    name: prometheus
    state: reloaded

- name: restart prometheus
  service:
    name: prometheus
    state: restarted
